CREATE TABLE IF NOT EXISTS tbl_UrlQueue (
    URLId UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    URL TEXT NOT NULL,
    IsMoved BOOLEAN DEFAULT FALSE
);